# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=5)),
                ('LTP', models.CharField(max_length=5)),
                ('credits', models.IntegerField(default=0)),
                ('courseType', models.BooleanField(choices=[(1, 'Credit'), (0, 'Audit')], default='true')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('role', models.BooleanField(choices=[(1, 'Instructor'), (0, 'Student')], default='true')),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GMS.User')),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GMS.User')),
                ('branch', models.IntegerField(choices=[(1, 'CSE'), (2, 'EE'), (3, 'ME')], default=1)),
                ('batch', models.CharField(default='UG2014', max_length=6)),
                ('semester', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GMS.Instructor'),
        ),
    ]
