# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=5)),
                ('name', models.CharField(default=b'Unspecified', max_length=50)),
                ('LTP', models.CharField(max_length=5)),
                ('credits', models.IntegerField(choices=[(0, b'0'), (3, b'3'), (4, b'4'), (5, b'5')], default=0)),
                ('courseType', models.BooleanField(choices=[(1, b'Credit'), (0, b'Audit')], default=b'true')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_CSE',
            fields=[
                ('sem', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(to='GMS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_EE',
            fields=[
                ('sem', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(to='GMS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_ME',
            fields=[
                ('sem', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(to='GMS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('role', models.BooleanField(choices=[(1, b'Instructor'), (0, b'Student')], default=b'true')),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GMS.User')),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GMS.User')),
                ('branch', models.IntegerField(choices=[(1, b'CSE'), (2, b'EE'), (3, b'ME')], default=1)),
                ('batch', models.CharField(choices=[(b'1', b'UG2012'), (b'2', b'UG2013'), (b'3', b'UG2014'), (b'4', b'UG2015')], max_length=6)),
                ('semester', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GMS.Instructor'),
        ),
    ]
