# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GMS.Course'),
        ),
    ]
