# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_CSE',
            fields=[
                ('sem', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_EE',
            fields=[
                ('sem', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_ME',
            fields=[
                ('sem', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=b'Unspecified', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(choices=[(0, b'0'), (3, b'3'), (4, b'4'), (5, b'5')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[(b'1', b'UG2012'), (b'2', b'UG2013'), (b'3', b'UG2014'), (b'4', b'UG2015')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8')], default=1),
        ),
        migrations.AddField(
            model_name='courses_me',
            name='courses',
            field=models.ManyToManyField(to='GMS.Course'),
        ),
        migrations.AddField(
            model_name='courses_ee',
            name='courses',
            field=models.ManyToManyField(to='GMS.Course'),
        ),
        migrations.AddField(
            model_name='courses_cse',
            name='courses',
            field=models.ManyToManyField(to='GMS.Course'),
        ),
    ]
