# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMS', '0002_auto_20160304_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gradesUploaded',
            field=models.BooleanField(default='false'),
        ),
    ]
