# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMS', '0002_auto_20160305_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Instructor'), (2, 'Admin')], default=0),
        ),
    ]
