# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMS', '0003_course_gradesuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseType',
            field=models.BooleanField(choices=[(0, 'Audit'), (1, 'Credit')], default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradesUploaded',
            field=models.BooleanField(default=False),
        ),
    ]
